### ISSUE TITLE
Using RuneLite's "Swap left click" feature reverts to "Use" in the bank and deposit box despite this plugin being installed

### ISSUE THREAD

**Issue by Nyny2121** [DominickCobb-rs/Empty-Forestry-Basket#2]

**Comment by DominickCobb-rs** [comment]
Are you suggesting the top left test isn't right?
![image](https://github.com/DominickCobb-rs/Empty-Forestry-Basket/assets/138266282/ab756dad-969b-4e7e-816c-5a8c0fb8741f)
Or are you suggesting the right click menu for the Forestry Basket isn't displaying correctly?

Currently it doesn't change the text in the top left if you swap left click on the item. Wasn't super concerned with that as much as I was with the right click menu more clearly saying "Empty" instead of "Use".

**Comment by Nyny2121** [comment]
![image](https://github.com/DominickCobb-rs/Empty-Forestry-Basket/assets/17759774/bcd16418-2851-4087-8635-1fc89d6d9964)
![image](https://github.com/DominickCobb-rs/Empty-Forestry-Basket/assets/17759774/9410c693-e347-49da-b076-1d31c339ec49)
![image](https://github.com/DominickCobb-rs/Empty-Forestry-Basket/assets/17759774/f88ddfbb-88b1-440c-8afa-b9cee56fb9f3)
![image](https://github.com/DominickCobb-rs/Empty-Forestry-Basket/assets/17759774/7371f24d-5bad-40bd-82a0-7a71c1a1cd96)


Upon further investigation, it would seem that it is a little weirder than I thought. I used the RuneLite entry swapper to set "Empty" to the left-click option in the bank, and when I initially clicked it it gave me the message that I was withdrawing leaves from my bank, so I thought the entry swapper was not working. However, when I went to take these screenshots, I found that every other time I click it it will either empty the basket or fill it, alternating back and forth.

For the visual "Use" showing up in the top left, I totally understand not wanting to mess with it since it's just a visual bug, but this other behavior is odd and I figured you would like it reported.

Thank you!

**Comment by Nyny2121** [comment]
Actually, I just tested it with and without the plugin, and the behavior is exactly the same either way. Clicking "Use" twice will toggle back and forth between filling and emptying the basket. This plugin just changes the text to "Empty." I think I am now realizing that this plugin is just intended to change the text of the menu entry, not the actual functionality - I thought that this plugin was making it so that left clicking on the forestry kit would only ever empty it and not fill it.

**Comment by DominickCobb-rs** [comment]
That's correct. Perhaps I'll change the text to "Empty/Fill". Unsure how it determines whether it's going to empty or fill.

**Comment by DominickCobb-rs** [comment]
~~Resolved with b6c0aaa4cf9e9415ce70a06aec1de5a737764fa1~~

**Comment by DominickCobb-rs** [comment]
Actually solved with 3303da263c2e7718ac786d3dfc5a66d6089c4c22. 
![image](https://github.com/user-attachments/assets/f73ae79a-f3f1-4123-b8de-57cdfc54196f)
